# Generated by Django 5.2.7 on 2025-11-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='irrigation_type',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='farmer',
            name='admin_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
