# Generated by Django 5.2.7 on 2025-12-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='irrigation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
