# Generated by Django 5.2.7 on 2025-12-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_land_country_land_irrigation_type_land_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('irrigation_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('total_acres_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmer.farmer')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmer.land')),
            ],
        ),
        migrations.CreateModel(
            name='CropAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=7)),
                ('seed_variety', models.CharField(blank=True, max_length=100)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('expected_yield_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmer.cropplan')),
            ],
        ),
    ]
