# Generated by Django 5.2.7 on 2025-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_cropplan_cropallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropallocation',
            name='seed_variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
