# Generated by Django 5.2.7 on 2025-12-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_alter_cropallocation_seed_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='admin_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
