# Generated by Django 5.2.7 on 2025-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_cropplan_admin_remark_cropplan_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropYieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(blank=True, choices=[('Alluvial', 'Alluvial'), ('Black', 'Black'), ('Red', 'Red'), ('Laterite', 'Laterite'), ('Desert', 'Desert'), ('Mountain', 'Mountain'), ('Sandy Loam', 'Sandy Loam'), ('Clay Loam', 'Clay Loam')], default='', max_length=50)),
                ('season', models.CharField(blank=True, choices=[('Kharif (Monsoon)', 'Kharif (Monsoon)'), ('Rabi (Winter)', 'Rabi (Winter)'), ('Zaid (Summer)', 'Zaid (Summer)'), ('Perennial (All Year)', 'Perennial (All Year)')], default='', max_length=50)),
                ('irrigation_type', models.CharField(blank=True, choices=[('Rainfed', 'Rainfed'), ('Canal', 'Canal'), ('Tube well', 'Tube well'), ('Drip', 'Drip'), ('Sprinkler', 'Sprinkler')], default='', max_length=50)),
                ('yield_quintals_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop Yield Config',
                'verbose_name_plural': 'Crop Yield Configs',
                'unique_together': {('crop_name', 'soil_type', 'season', 'irrigation_type')},
            },
        ),
    ]
