# Generated by Django 5.2.7 on 2025-12-10 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
