# Generated by Django 5.2.7 on 2025-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Account',
                'verbose_name_plural': 'Admin Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='FarmerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Farmer Account',
                'verbose_name_plural': 'Farmer Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin')], default='farmer', max_length=10),
        ),
    ]
