# Generated by Django 5.2.7 on 2025-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminaccount_farmeraccount_account_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
