# Generated by Django 5.2.7 on 2025-11-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_planned', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.season')),
            ],
        ),
    ]
